cask "cline-desktop" do
  version "0.0.37"
  sha256 "d775219c05748a5bd442422c6f7ac3c009144a0ea43f85ad20e4de051ba67e48"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/cline-desktop-v#{version}/cline-desktop-#{version}-x86_64.AppImage"
  name "Cline Desktop"
  desc "AI coding agent desktop app"
  homepage "https://cline.bot/"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^cline-desktop-v(\d+\.\d+\.\d+(?:[.-]\w+)*)$/)
    strategy :git
  end

  auto_updates false
  depends_on arch: :x86_64
  depends_on :linux

  app_image "cline-desktop-#{version}-x86_64.AppImage", target: "cline-desktop-x86_64.AppImage"
  binary "cline-desktop-#{version}-x86_64.AppImage", target: "cline-app"

  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/cline-app", args: ["--appimage-extract"], chdir: "{{staged_path}}"
    copy "squashfs-root/cline-desktop.png",
         ".local/share/icons/hicolor/256x256/apps/cline-desktop.png",
         target_base: :home
    remove "{{staged_path}}/squashfs-root", recursive: true
    write_file ".local/share/applications/cline-desktop.desktop", <<~EOS, base: :home
      # generated by brew cask install steps
      [Desktop Entry]
      Name=Cline
      Comment=Cline AI coding agent
      Exec="{{HOMEBREW_PREFIX}}/bin/cline-app"
      Icon=cline-desktop
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Development;
      StartupWMClass=cline-app
    EOS
  end

  zap trash: [
    "~/.cache/bot.cline.app",
    "~/.cline",
    "~/.config/bot.cline.app",
    "~/.local/share/applications/cline-desktop.desktop",
    "~/.local/share/bot.cline.app",
    "~/.local/share/icons/hicolor/256x256/apps/cline-desktop.png",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
    The desktop entry and icon are only removed by the zap stanza. If you uninstalled
    without --zap, clean them up with:
      brew uninstall --zap --force cline-desktop
  EOS
end
