cask "commandcode-desktop" do
  version "0.1.29"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/commandcode-desktop-v#{version}/commandcode-desktop-#{version}-x86_64.AppImage"
  name "Command Code Desktop"
  desc "AI coding agent desktop app"
  homepage "https://commandcode.ai/desktop"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^commandcode-desktop-v(\d+\.\d+\.\d+(?:[.-]\w+)*)$/)
    strategy :git
  end

  auto_updates false
  depends_on arch: :x86_64
  depends_on :linux

  app_image "commandcode-desktop-#{version}-x86_64.AppImage", target: "commandcode-desktop-x86_64.AppImage"
  binary "commandcode-desktop-#{version}-x86_64.AppImage", target: "command-code"

  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/command-code", args: ["--appimage-extract"], chdir: "{{staged_path}}"
    copy "squashfs-root/commandcode-desktop.png",
         ".local/share/icons/hicolor/512x512/apps/commandcode-desktop.png",
         target_base: :home
    remove "{{staged_path}}/squashfs-root", recursive: true
    write_file ".local/share/applications/commandcode-desktop.desktop", <<~EOS, base: :home
      # generated by brew cask install steps
      [Desktop Entry]
      Name=Command Code
      Comment=Command Code desktop app
      Exec="{{HOMEBREW_PREFIX}}/bin/command-code" %U
      Icon=commandcode-desktop
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Development;
      StartupWMClass=command-code
      MimeType=x-scheme-handler/commandcode;
    EOS
  end

  zap trash: [
    "~/.config/@commandcodedesktop-updater",
    "~/.local/share/applications/commandcode-desktop.desktop",
    "~/.local/share/icons/hicolor/512x512/apps/commandcode-desktop.png",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
    The desktop entry and icon are only removed by the zap stanza. If you uninstalled
    without --zap, clean them up with:
      brew uninstall --zap --force commandcode-desktop
  EOS
end
