cask "firefox" do
  version "157.0.1"
  sha256 "8cb4c936932d3207442d55f6d1bd7c44d1ff7adeeaa2e1fe01e895bb4f1e1773"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/firefox-v#{version}/firefox-#{version}-x86_64.AppImage"
  name "Firefox"
  desc "Repackage of Mozilla Firefox as an AppImage"
  homepage "https://www.mozilla.org/firefox/"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^firefox-v(\d+\.\d+(?:\.\d+)*)$/)
    strategy :git
  end

  auto_updates false
  depends_on arch: :x86_64
  depends_on :linux

  app_image "firefox-#{version}-x86_64.AppImage", target: "firefox-x86_64.AppImage"
  binary "firefox-#{version}-x86_64.AppImage", target: "firefox"

  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/firefox", args: ["--appimage-extract"], chdir: "{{staged_path}}"
    copy "squashfs-root/firefox.png",
         ".local/share/icons/hicolor/128x128/apps/firefox.png",
         target_base: :home
    remove "{{staged_path}}/squashfs-root", recursive: true
    write_file ".local/share/applications/firefox.desktop", <<~EOS, base: :home
      # generated by brew cask install steps
      [Desktop Entry]
      Name=Firefox
      Comment=Fast, private, open-source web browser
      Exec="{{HOMEBREW_PREFIX}}/bin/firefox" %u
      Icon=firefox
      Terminal=false
      Type=Application
      StartupNotify=true
      StartupWMClass=firefox
      Categories=Network;WebBrowser;
      MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/mailto;
    EOS
  end

  zap trash: [
    "~/.cache/mozilla",
    "~/.config/mozilla",
    "~/.local/share/applications/firefox.desktop",
    "~/.local/share/icons/hicolor/128x128/apps/firefox.png",
    "~/.mozilla",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
    The desktop entry and icon are only removed by the zap stanza. If you uninstalled
    without --zap, clean them up with:
      brew uninstall --zap --force firefox
  EOS
end
