cask "freebuff-desktop" do
  arch arm: "aarch64", intel: "x86_64"

  version "0.0.109"
  sha256 arm64_linux:  "03e40e47aebefddf75a50f43648abd6ea260097bf161a8c43e25d872f3edbb72",
         x86_64_linux: "e96151f990ed6d45272b998fc9e4f15a4a725abb34ab7452b49a03c5321bc243"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/freebuff-desktop-v#{version}/freebuff-desktop-#{version}-#{arch}.AppImage"
  name "Freebuff"
  desc "Community desktop app from Codebuff"
  homepage "https://freebuff.com/"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^freebuff-desktop-v(\d+\.\d+\.\d+(?:[.-]\w+)*)$/)
    strategy :git
  end

  auto_updates false
  depends_on :linux

  app_image "freebuff-desktop-#{version}-#{arch}.AppImage", target: "freebuff-desktop-#{arch}.AppImage"
  binary "freebuff-desktop-#{version}-#{arch}.AppImage", target: "freebuff-desktop"

  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/freebuff-desktop", args: ["--appimage-extract"], chdir: "{{staged_path}}"
    copy "squashfs-root/freebuff-desktop.png",
         ".local/share/icons/hicolor/512x512/apps/freebuff-desktop.png",
         target_base: :home
    remove "{{staged_path}}/squashfs-root", recursive: true
    write_file ".local/share/applications/freebuff-desktop.desktop", <<~EOS, base: :home
      # generated by brew cask install steps
      [Desktop Entry]
      Name=Freebuff
      Comment=Freebuff Desktop
      Exec="{{HOMEBREW_PREFIX}}/bin/freebuff-desktop" %U
      Icon=freebuff-desktop
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Development;
      StartupWMClass=Freebuff
    EOS
  end

  zap trash: [
    "~/.cache/Freebuff",
    "~/.config/@codebufffreebuff-desktop-updater",
    "~/.config/Freebuff",
    "~/.local/share/applications/freebuff-desktop.desktop",
    "~/.local/share/Freebuff",
    "~/.local/share/icons/hicolor/512x512/apps/freebuff-desktop.png",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
    The desktop entry and icon are only removed by the zap stanza. If you uninstalled
    without --zap, clean them up with:
      brew uninstall --zap --force freebuff-desktop
  EOS
end
