cask "gitbutler" do
  arch arm: "aarch64", intel: "x86_64"

  version "0.22.3"
  sha256 arm64_linux:  "07a5f26ba99d0e005acd273a3f4309343c0b60b5347c7c8f2d5386d10f696d4f",
         x86_64_linux: "33204f9519b4af7ce60040b6e6d0335e166d6559c37f842469f9de6a11de8888"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/gitbutler-v#{version}/gitbutler-#{version}-#{arch}.AppImage"
  name "GitButler"
  desc "Git, finally designed for humans"
  homepage "https://gitbutler.com/"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^gitbutler-v(\d+\.\d+\.\d+(?:[.-]\w+)*)$/)
    strategy :git
  end

  auto_updates false
  depends_on :linux

  app_image "gitbutler-#{version}-#{arch}.AppImage", target: "gitbutler-#{arch}.AppImage"
  binary "gitbutler-#{version}-#{arch}.AppImage", target: "gitbutler-tauri"
  binary "gitbutler-#{version}-#{arch}.AppImage", target: "but"

  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/gitbutler-tauri", args: ["--appimage-extract"], chdir: "{{staged_path}}"
    copy "squashfs-root/gitbutler.png", "~/.local/share/icons/hicolor/128x128/apps/gitbutler.png"
    remove "{{staged_path}}/squashfs-root", recursive: true
    write_file "~/.local/share/applications/gitbutler.desktop", <<~EOS
      # generated by brew cask install steps
      [Desktop Entry]
      Name=GitButler
      Comment=Git, finally designed for humans
      Exec="{{HOMEBREW_PREFIX}}/bin/gitbutler-tauri" %U
      Icon=gitbutler
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Development;
      StartupWMClass=gitbutler-tauri
      MimeType=x-scheme-handler/but;
    EOS
  end

  zap trash: [
    "~/.cache/gitbutler",
    "~/.config/com.gitbutler.app",
    "~/.config/gitbutler",
    "~/.local/share/applications/gitbutler.desktop",
    "~/.local/share/com.gitbutler.app",
    "~/.local/share/gitbutler",
    "~/.local/share/icons/hicolor/128x128/apps/gitbutler.png",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
    The desktop entry and icon are only removed by the zap stanza. If you uninstalled
    without --zap, clean them up with:
      brew uninstall --zap --force gitbutler
  EOS
end
