cask "gitbutler" do
  arch arm: "aarch64", intel: "x86_64"

  version "0.22.1"
  sha256 arm64_linux:  "418a75523cd0adf1a74b3579c85afc08d0fcab78bbc26cc8b74db755cccd3f03",
         x86_64_linux: "06f80ba50cc2c73d99d83c3d998c997f2532aae2498145fbe369f355d737b7b2"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/gitbutler-v#{version}/gitbutler-#{version}-#{arch}.AppImage",
      verified: "github.com/edgarcnp/homebrew-tap"
  name "GitButler"
  desc "Git, finally designed for humans"
  homepage "https://gitbutler.com/"

  livecheck do
    url "https://api.github.com/repos/edgarcnp/homebrew-tap/releases?per_page=100"
    strategy :json do |json|
      versions = json.filter_map do |release|
        next if release["draft"] || release["prerelease"]

        tag = release["tag_name"]
        next unless tag&.start_with?("gitbutler-v")

        candidate = tag.delete_prefix("gitbutler-v")
        next if candidate.empty?
        next unless candidate.match?(/\A\d+\.\d+\.\d+(?:[.-]\w+)*\z/)

        candidate
      end
      versions.max_by { |candidate| Gem::Version.new(candidate) }
    end
  end

  auto_updates false
  depends_on :linux

  app_image "gitbutler-#{version}-#{arch}.AppImage"
  binary "gitbutler-#{version}-#{arch}.AppImage", target: "gitbutler-tauri"
  binary "gitbutler-#{version}-#{arch}.AppImage", target: "but"
  artifact "gitbutler.desktop", target: "#{Dir.home}/.local/share/applications/gitbutler.desktop"

  preflight do
    FileUtils.chmod "+x", staged_path/"gitbutler-#{version}-#{arch}.AppImage"
    system(staged_path/"gitbutler-#{version}-#{arch}.AppImage", "--appimage-extract",
           chdir: staged_path) || odie("AppImage extraction failed")

    icon_dir = "#{Dir.home}/.local/share/icons/hicolor/256x256/apps" # 256x256 per upstream build-appimage.sh
    applications_dir = "#{Dir.home}/.local/share/applications"
    FileUtils.mkdir_p [icon_dir, applications_dir]

    icon_source = staged_path/"squashfs-root/gitbutler.png"
    odie "Icon source not found: #{icon_source}" unless icon_source.exist?

    FileUtils.cp icon_source, "#{icon_dir}/gitbutler.png"
    FileUtils.rm_r(staged_path/"squashfs-root")

    File.write(staged_path/"gitbutler.desktop", <<~EOS)
      # generated by cask preflight
      [Desktop Entry]
      Name=GitButler
      Comment=Git, finally designed for humans
      Exec="#{HOMEBREW_PREFIX}/bin/gitbutler-tauri" %U
      Icon=gitbutler
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Development;
      StartupWMClass=gitbutler-tauri
      MimeType=x-scheme-handler/but;
    EOS
  end

  uninstall delete: [
    "#{Dir.home}/.local/share/applications/gitbutler.desktop",
    "#{Dir.home}/.local/share/icons/hicolor/256x256/apps/gitbutler.png",
  ]

  zap trash: [
    "~/.cache/gitbutler",
    "~/.config/gitbutler",
    "~/.local/share/applications/gitbutler.desktop",
    "~/.local/share/gitbutler",
    "~/.local/share/icons/hicolor/256x256/apps/gitbutler.png",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
  EOS
end
