cask "gitcomet" do
  arch arm: "aarch64", intel: "x86_64"

  version "0.2.5"
  sha256 arm64_linux:  "e495d1a196487ff11e928f3ce9fb6d787b69f45c8747b6a64459f021472c071e",
         x86_64_linux: "701299dfd8f06d8ae98a8944c71e9bfb5e2221d79cea7e96d4f5379e8272a735"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/gitcomet-v#{version}/gitcomet-#{version}-#{arch}.AppImage"
  name "GitComet"
  desc "Fast, resource-efficient Git GUI written in Rust"
  homepage "https://gitcomet.dev/"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^gitcomet-v(\d+\.\d+\.\d+(?:[.-]\w+)*)$/)
    strategy :git
  end

  auto_updates false
  depends_on :linux

  app_image "gitcomet-#{version}-#{arch}.AppImage", target: "gitcomet-#{arch}.AppImage"
  binary "gitcomet-#{version}-#{arch}.AppImage", target: "gitcomet"

  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/gitcomet", args: ["--appimage-extract"], chdir: "{{staged_path}}"
    copy "squashfs-root/gitcomet.png",
         ".local/share/icons/hicolor/512x512/apps/gitcomet.png",
         target_base: :home
    remove "{{staged_path}}/squashfs-root", recursive: true
    write_file ".local/share/applications/gitcomet.desktop", <<~EOS, base: :home
      # generated by brew cask install steps
      [Desktop Entry]
      Name=GitComet
      Comment=Fast, resource-efficient Git GUI written in Rust
      Exec="{{HOMEBREW_PREFIX}}/bin/gitcomet"
      Icon=gitcomet
      Terminal=false
      Type=Application
      StartupWMClass=gitcomet
      Categories=Development;RevisionControl;
    EOS
  end

  zap trash: [
    "~/.local/share/applications/gitcomet.desktop",
    "~/.local/share/gitcomet",
    "~/.local/share/icons/hicolor/512x512/apps/gitcomet.png",
    "~/.local/state/gitcomet",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
    The desktop entry and icon are only removed by the zap stanza. If you uninstalled
    without --zap, clean them up with:
      brew uninstall --zap --force gitcomet
  EOS
end
