cask "little-genius" do
  version "0.6.7"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/little-genius-v#{version}/little-genius-#{version}-x86_64.AppImage"
  name "Little Genius"
  desc "Soulframe companion app"
  homepage "https://lg.avakot.org/"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^little-genius-v(\d+\.\d+\.\d+(?:[.-]\w+)*)$/)
    strategy :git
  end

  auto_updates false
  depends_on arch: :x86_64
  depends_on :linux

  app_image "little-genius-#{version}-x86_64.AppImage", target: "little-genius-x86_64.AppImage"
  binary "little-genius-#{version}-x86_64.AppImage", target: "little-genius"
  binary "little-genius-#{version}-x86_64.AppImage", target: "lg-linux-compat"

  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/little-genius", args: ["--appimage-extract"], chdir: "{{staged_path}}"
    copy "squashfs-root/little-genius.png",
         ".local/share/icons/hicolor/512x512/apps/little-genius.png",
         target_base: :home
    remove "{{staged_path}}/squashfs-root", recursive: true
    write_file ".local/share/applications/little-genius.desktop", <<~EOS, base: :home
      # generated by brew cask install steps
      [Desktop Entry]
      Name=Little Genius
      Comment=The Soulframe Companion App
      Exec="{{HOMEBREW_PREFIX}}/bin/little-genius" %U
      Icon=little-genius
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Utility;
      StartupWMClass=little-genius
      MimeType=x-scheme-handler/avakot-lg;
    EOS
  end

  zap trash: [
    "~/.local/share/applications/little-genius.desktop",
    "~/.local/share/icons/hicolor/512x512/apps/little-genius.png",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
    The desktop entry and icon are only removed by the zap stanza. If you uninstalled
    without --zap, clean them up with:
      brew uninstall --zap --force little-genius
  EOS
end
