cask "opencode-desktop" do
  version "2.0.16"
  sha256 "f1cfafa59de30517328bb2a5145d29014b3335df3f2f88812ae15f52ef59e1ec"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/opencode-desktop-v#{version}/opencode-desktop-#{version}-x86_64.AppImage"
  name "OpenCode Desktop"
  desc "Open source AI coding agent"
  homepage "https://opencode.ai/"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^opencode-desktop-v(\d+\.\d+\.\d+(?:[.-]\w+)*)$/)
    strategy :git
  end

  auto_updates false
  depends_on arch: :x86_64
  depends_on :linux

  app_image "opencode-desktop-#{version}-x86_64.AppImage", target: "opencode-desktop-x86_64.AppImage"
  binary "opencode-desktop-#{version}-x86_64.AppImage", target: "opencode-desktop"

  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/opencode-desktop", args: ["--appimage-extract"], chdir: "{{staged_path}}"
    copy "squashfs-root/opencode-desktop.png",
         ".local/share/icons/hicolor/128x128/apps/opencode-desktop.png",
         target_base: :home
    remove "{{staged_path}}/squashfs-root", recursive: true
    write_file ".local/share/applications/opencode-desktop.desktop", <<~EOS, base: :home
      # generated by brew cask install steps
      [Desktop Entry]
      Name=OpenCode
      Comment=Open source AI coding agent
      Exec="{{HOMEBREW_PREFIX}}/bin/opencode-desktop" %U
      Icon=opencode-desktop
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Development;
      StartupWMClass=ai.opencode.desktop
      MimeType=x-scheme-handler/opencode;
    EOS
  end

  zap trash: [
    "~/.cache/ai.opencode.desktop",
    "~/.config/ai.opencode.desktop",
    "~/.local/share/ai.opencode.desktop",
    "~/.local/share/applications/opencode-desktop.desktop",
    "~/.local/share/icons/hicolor/128x128/apps/opencode-desktop.png",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
    The desktop entry and icon are only removed by the zap stanza. If you uninstalled
    without --zap, clean them up with:
      brew uninstall --zap --force opencode-desktop
  EOS
end
