cask "opencode-desktop" do
  arch arm: "aarch64", intel: "x86_64"

  version "2.0.12"
  sha256 arm64_linux:  "6ee356efba5396e25612243a76320089b5e6e126137d0ea406b8ac92a4bf4db8",
         x86_64_linux: "4fc68fdf98978028e6cc6d0081c70bb1ea4ab4d5203938babda5f17db6f6e1c4"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/opencode-desktop-v#{version}/opencode-desktop-#{version}-#{arch}.AppImage"
  name "OpenCode Desktop"
  desc "Open source AI coding agent"
  homepage "https://opencode.ai/"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^opencode-desktop-v(\d+\.\d+\.\d+(?:[.-]\w+)*)$/)
    strategy :git
  end

  auto_updates false
  depends_on :linux

  app_image "opencode-desktop-#{version}-#{arch}.AppImage", target: "opencode-desktop-#{arch}.AppImage"
  binary "opencode-desktop-#{version}-#{arch}.AppImage", target: "opencode-desktop"

  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/opencode-desktop", args: ["--appimage-extract"], chdir: "{{staged_path}}"
    copy "squashfs-root/opencode-desktop.png",
         ".local/share/icons/hicolor/128x128/apps/opencode-desktop.png",
         target_base: :home
    remove "{{staged_path}}/squashfs-root", recursive: true
    write_file ".local/share/applications/opencode-desktop.desktop", <<~EOS, base: :home
      # generated by brew cask install steps
      [Desktop Entry]
      Name=OpenCode
      Comment=Open source AI coding agent
      Exec="{{HOMEBREW_PREFIX}}/bin/opencode-desktop" %U
      Icon=opencode-desktop
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Development;
      StartupWMClass=ai.opencode.desktop
      MimeType=x-scheme-handler/opencode;
    EOS
  end

  zap trash: [
    "~/.cache/ai.opencode.desktop",
    "~/.config/ai.opencode.desktop",
    "~/.local/share/ai.opencode.desktop",
    "~/.local/share/applications/opencode-desktop.desktop",
    "~/.local/share/icons/hicolor/128x128/apps/opencode-desktop.png",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
    The desktop entry and icon are only removed by the zap stanza. If you uninstalled
    without --zap, clean them up with:
      brew uninstall --zap --force opencode-desktop
  EOS
end
