cask "spotifast" do
  version "0.12.0"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/spotifast-v#{version}/spotifast-#{version}-x86_64.AppImage"
  name "Spotifast"
  desc "Native Spotify client"
  homepage "https://github.com/crmne/spotifast"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^spotifast-v(\d+\.\d+\.\d+(?:[.-]\w+)*)$/)
    strategy :git
  end

  auto_updates false
  depends_on arch: :x86_64
  depends_on :linux

  app_image "spotifast-#{version}-x86_64.AppImage", target: "spotifast-x86_64.AppImage"
  binary "spotifast-#{version}-x86_64.AppImage", target: "spotifast"

  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/spotifast", args: ["--appimage-extract"], chdir: "{{staged_path}}"
    copy "squashfs-root/spotifast.svg",
         ".local/share/icons/hicolor/scalable/apps/spotifast.svg",
         target_base: :home
    remove "{{staged_path}}/squashfs-root", recursive: true
    write_file ".local/share/applications/spotifast.desktop", <<~EOS, base: :home
      # generated by brew cask install steps
      [Desktop Entry]
      Name=Spotifast
      Comment=Native Spotify client
      Exec="{{HOMEBREW_PREFIX}}/bin/spotifast" %u
      Icon=spotifast
      Terminal=false
      Type=Application
      StartupNotify=true
      StartupWMClass=spotifast
      Categories=AudioVideo;Audio;Player;Music;
      MimeType=x-scheme-handler/spotify;
    EOS
  end

  zap trash: [
    "~/.cache/spotifast",
    "~/.config/spotifast",
    "~/.local/share/applications/spotifast.desktop",
    "~/.local/share/icons/hicolor/scalable/apps/spotifast.svg",
    "~/.local/state/spotifast",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
    The desktop entry and icon are only removed by the zap stanza. If you uninstalled
    without --zap, clean them up with:
      brew uninstall --zap --force spotifast
  EOS
end
