cask "vscode" do
  arch arm: "aarch64", intel: "x86_64"

  version "1.135.0"
  sha256 arm64_linux:  "6b8fe0ccdb73a347c70bbfc5e682eb757a1b97475abb2c7e898d113d4cc27b67",
         x86_64_linux: "fd4773133228ce03bfe4f5796374f45c03a9a3ffc5e66cd821ed8eca295a8004"

  xdg_data_home = ENV.fetch("XDG_DATA_HOME", File.join(Dir.home, ".local", "share"))
  xdg_config_home = ENV.fetch("XDG_CONFIG_HOME", File.join(Dir.home, ".config"))
  xdg_cache_home = ENV.fetch("XDG_CACHE_HOME", File.join(Dir.home, ".cache"))

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/vscode-v#{version}/vscode-#{version}-#{arch}.AppImage",
      verified: "github.com/edgarcnp/homebrew-tap"
  name "Visual Studio Code"
  desc "Repackage of Visual Studio Code as an AppImage"
  homepage "https://code.visualstudio.com/"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^vscode-v(\d+\.\d+\.\d+(?:[.-]\w+)*)$/)
    strategy :git
  end

  auto_updates false
  conflicts_with cask: ["visual-studio-code", "vscodium"]
  depends_on :linux

  app_image "vscode-#{version}-#{arch}.AppImage"
  binary "vscode-#{version}-#{arch}.AppImage", target: "code"

  preflight do
    FileUtils.chmod "+x", staged_path/"vscode-#{version}-#{arch}.AppImage"
    system(staged_path/"vscode-#{version}-#{arch}.AppImage", "--appimage-extract",
           chdir: staged_path) || odie("AppImage extraction failed")

    icon_dir = "#{xdg_data_home}/icons/hicolor/256x256/apps" # 256x256 per upstream build-appimage.sh
    applications_dir = "#{xdg_data_home}/applications"
    FileUtils.mkdir_p [icon_dir, applications_dir]

    icon_source = staged_path/"squashfs-root/vscode.png"
    odie "Icon source not found: #{icon_source}" unless icon_source.exist?

    FileUtils.cp icon_source, "#{icon_dir}/vscode.png"
    FileUtils.rm_r(staged_path/"squashfs-root")

    File.write("#{applications_dir}/vscode.desktop", <<~EOS)
      # generated by cask preflight
      [Desktop Entry]
      Name=Visual Studio Code
      Comment=Code Editing. Redefined.
      Exec="#{HOMEBREW_PREFIX}/bin/code" %F
      Icon=vscode
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Development;
      MimeType=application/x-code-workspace;
      StartupWMClass=Code
    EOS
  end

  uninstall trash: [
    "#{xdg_data_home}/applications/vscode.desktop",
    "#{xdg_data_home}/icons/hicolor/256x256/apps/vscode.png",
  ]

  zap trash: [
    "#{Dir.home}/.vscode-cli",
    "#{Dir.home}/.vscode-server",
    "#{xdg_cache_home}/Code",
    "#{xdg_config_home}/Code",
    "#{xdg_data_home}/applications/vscode.desktop",
    "#{xdg_data_home}/icons/hicolor/256x256/apps/vscode.png",
    "~/.vscode",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
  EOS
end
