cask "vscode" do
  arch arm: "aarch64", intel: "x86_64"

  version "1.135.0"
  sha256 arm64_linux:  "06a9ca846ffa131d92c3d58c07b30573097ec4ac807deffa35d42868e9025b22",
         x86_64_linux: "58f5010f5a697cfec72481c9d6161d4585abf6cc6a29fda1beaa2fa62701a06b"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/vscode-v#{version}/vscode-#{version}-#{arch}.AppImage",
       verified: "github.com/edgarcnp/homebrew-tap"
  name "Visual Studio Code"
  desc "Repackage of Visual Studio Code as an AppImage"
  homepage "https://code.visualstudio.com/"

  livecheck do
    url "https://api.github.com/repos/edgarcnp/homebrew-tap/releases?per_page=100"
    strategy :json do |json|
      versions = json.filter_map do |release|
        next if release["draft"] || release["prerelease"]

        tag = release["tag_name"]
        next unless tag&.start_with?("vscode-v")

        candidate = tag.delete_prefix("vscode-v")
        next if candidate.empty?
        next unless candidate.match?(/\A\d+\.\d+\.\d+(?:[.-]\w+)*\z/)

        candidate
      end
      versions.max_by { |candidate| Gem::Version.new(candidate) }
    end
  end

  depends_on :linux
  auto_updates false
  conflicts_with cask: ["visual-studio-code", "code", "vscodium"]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
  EOS

  app_image "vscode-#{version}-#{arch}.AppImage"
  binary "vscode-#{version}-#{arch}.AppImage", target: "code"
  artifact "vscode.desktop", target: "#{Dir.home}/.local/share/applications/vscode.desktop"

  uninstall delete: [
    "#{Dir.home}/.local/share/applications/vscode.desktop",
    "#{Dir.home}/.local/share/icons/hicolor/256x256/apps/vscode.png",
  ]

  preflight do
    FileUtils.chmod "+x", staged_path/"vscode-#{version}-#{arch}.AppImage"
    system(staged_path/"vscode-#{version}-#{arch}.AppImage", "--appimage-extract",
           chdir: staged_path) || odie("AppImage extraction failed")

    icon_dir = "#{Dir.home}/.local/share/icons/hicolor/256x256/apps" # 256x256 per upstream build-appimage.sh
    applications_dir = "#{Dir.home}/.local/share/applications"
    FileUtils.mkdir_p [icon_dir, applications_dir]

    icon_source = staged_path/"squashfs-root/vscode.png"
    odie "Icon source not found: #{icon_source}" unless icon_source.exist?

    FileUtils.cp icon_source, "#{icon_dir}/vscode.png"
    FileUtils.rm_r(staged_path/"squashfs-root")

    File.write(staged_path/"vscode.desktop", <<~EOS)
      # generated by cask preflight
      [Desktop Entry]
      Name=Visual Studio Code
      Comment=Code Editing. Redefined.
      Exec="#{HOMEBREW_PREFIX}/bin/code" %F
      Icon=vscode
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Development;
      MimeType=application/x-code-workspace;
      StartupWMClass=Code
    EOS
  end

  zap trash: [
    "~/.cache/Code",
    "~/.config/Code",
    "~/.local/share/applications/vscode.desktop",
    "~/.local/share/icons/hicolor/256x256/apps/vscode.png",
    "~/.vscode",
  ]
end
