cask "wfhelper" do
  version "2.1.0"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  url "https://github.com/edgarcnp/homebrew-tap/releases/download/wfhelper-v#{version}/wfhelper-#{version}-x86_64.AppImage"
  name "WFHelper"
  desc "Warframe companion app"
  homepage "https://github.com/WFHelper/WFHelper"

  livecheck do
    url "https://github.com/edgarcnp/homebrew-tap.git"
    regex(/^wfhelper-v(\d+\.\d+\.\d+(?:[.-]\w+)*)$/)
    strategy :git
  end

  auto_updates false
  depends_on arch: :x86_64
  depends_on :linux

  app_image "wfhelper-#{version}-x86_64.AppImage", target: "wfhelper-x86_64.AppImage"
  binary "wfhelper-#{version}-x86_64.AppImage", target: "wfhelper"

  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/wfhelper", args: ["--appimage-extract"], chdir: "{{staged_path}}"
    copy "squashfs-root/wfhelper.png",
         ".local/share/icons/hicolor/974x974/apps/wfhelper.png",
         target_base: :home
    remove "{{staged_path}}/squashfs-root", recursive: true
    write_file ".local/share/applications/wfhelper.desktop", <<~EOS, base: :home
      # generated by brew cask install steps
      [Desktop Entry]
      Name=WFHelper
      Comment=Warframe companion: inventory, foundry, relic and riven scanning, market orders.
      Exec="{{HOMEBREW_PREFIX}}/bin/wfhelper" %U
      Icon=wfhelper
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Utility;
      StartupWMClass=wfhelper
    EOS
  end

  zap trash: [
    "~/.config/wfhelper",
    "~/.local/share/applications/wfhelper.desktop",
    "~/.local/share/icons/hicolor/974x974/apps/wfhelper.png",
  ]

  caveats <<~EOS
    This cask installs an AppImage that requires unprivileged user namespaces or FUSE.
    On some systems you may need to enable unprivileged_userns_clone or install FUSE3.
    The desktop entry and icon are only removed by the zap stanza. If you uninstalled
    without --zap, clean them up with:
      brew uninstall --zap --force wfhelper
  EOS
end
