# frozen_string_literal: true

require "fileutils"

# Shared helpers for the AppImage casks in this tap: XDG-aware paths and the
# preflight logic that extracts each AppImage, installs its icon and desktop
# entry, and cleans up. Keeping this in one module means install-logic
# changes land in a single place instead of all three casks.
module CaskHelpers
  def self.xdg_data_home
    ENV.fetch("XDG_DATA_HOME", File.join(Dir.home, ".local", "share"))
  end

  def self.xdg_config_home
    ENV.fetch("XDG_CONFIG_HOME", File.join(Dir.home, ".config"))
  end

  def self.xdg_cache_home
    ENV.fetch("XDG_CACHE_HOME", File.join(Dir.home, ".cache"))
  end

  # Desktop entry + icon paths installed by install_desktop_integration;
  # used by both uninstall and zap.
  def self.desktop_files(app_name, icon_dir:)
    [
      "#{xdg_data_home}/applications/#{app_name}.desktop",
      "#{xdg_data_home}/icons/hicolor/#{icon_dir}/apps/#{app_name}.png",
    ]
  end

  # Extracts the AppImage so its embedded icon can be read. Fails loudly on
  # extraction errors.
  def self.extract_appimage(appimage_path)
    FileUtils.chmod "+x", appimage_path.to_s
    system(appimage_path.to_s, "--appimage-extract", chdir: appimage_path.parent.to_s) ||
      raise("AppImage extraction failed")
  end

  # Renders the desktop entry written by install_desktop_integration.
  def self.desktop_entry(name:, comment:, exec:, icon:, wm_class:, mime_type:)
    <<~EOS
      # generated by cask preflight
      [Desktop Entry]
      Name=#{name}
      Comment=#{comment}
      Exec=#{exec}
      Icon=#{icon}
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=Development;
      StartupWMClass=#{wm_class}
      MimeType=#{mime_type}
    EOS
  end

  # Installs the extracted icon and a desktop entry under XDG data, then
  # removes the extraction directory (icon_path.parent, e.g. squashfs-root).
  def self.install_desktop_integration(app_name:, icon_path:, icon_dir:, entry:)
    applications_dir = "#{xdg_data_home}/applications"
    FileUtils.mkdir_p [icon_dir, applications_dir]
    raise "Icon source not found: #{icon_path}" unless icon_path.exist?

    FileUtils.cp icon_path, "#{icon_dir}/#{app_name}.png"
    FileUtils.rm_r(icon_path.parent)
    File.write("#{applications_dir}/#{app_name}.desktop", entry)
  end
end
